import os
import asyncio
import pandas as pd
import numpy as np
from datetime import datetime
from typing import List, Dict, Any, Optional

from app.core.engine import get_bs_price, calculate_indicators
from app.schemas.profile import StrategyProfile

class StrategyBacktester:
    def __init__(self, profile: StrategyProfile):
        self.profile = profile
        self.symbol = profile.symbol
        self.cache_dir = "backend/app/data/cache"
        self.cache_file = os.path.join(self.cache_dir, f"{self.symbol}_historical.csv")
        self.output_file = os.path.join(self.cache_dir, f"{self.symbol}_training_data.csv")
        
        # Ensure directory exists
        os.makedirs(self.cache_dir, exist_ok=True)

    def _load_historical_data(self) -> pd.DataFrame:
        """Loads historical data from local cache generated by the Optimizer."""
        if not os.path.exists(self.cache_file):
            raise FileNotFoundError(f"Cache for {self.symbol} not found. Run optimization first.")
        
        df = pd.read_csv(self.cache_file, index_col=0)
        df.index = pd.to_datetime(df.index, utc=True).tz_convert('US/Eastern')
        return df

    def simulate_campaign(self, df: pd.DataFrame, start_idx: int) -> int:
        """Ported from backtest.py simulation logic."""
        entry_row = df.iloc[start_idx]
        atr = entry_row['atr']
        z_score = entry_row['macd_z']
        
        opt_type = 'call' if z_score < 0 else 'put'
        direction = 1 if z_score < 0 else -1
        strike = round(entry_row['Close']) 
        t_start = self.profile.target_expiry_days / 365 
        vol = entry_row['implied_vol']
        
        contracts = self.profile.initial_size
        initial_opt_price = get_bs_price(entry_row['Close'], strike, t_start, self.profile.risk_free_rate, vol, opt_type)
        total_cost = initial_opt_price * contracts * 100
        
        future = df.iloc[start_idx + 1 : start_idx + 240] 
        for i, (ts, curr_row) in enumerate(future.iterrows()):
            mins_passed = i + 1
            t_current = (self.profile.target_expiry_days - (mins_passed / 390)) / 365
            curr_opt_price = get_bs_price(curr_row['Close'], strike, t_current, self.profile.risk_free_rate, vol, opt_type)
            
            # Scaling Logic
            moved_against = (direction == 1 and curr_row['Close'] < (entry_row['Close'] - (atr * self.profile.scale_in_step_atr))) or \
                            (direction == -1 and curr_row['Close'] > (entry_row['Close'] + (atr * self.profile.scale_in_step_atr)))
            
            if moved_against and contracts < self.profile.max_contracts:
                contracts += 1
                total_cost += curr_opt_price * 100
                
            # Exit: Reversion
            if (direction == 1 and curr_row['macd_z'] >= 0) or (direction == -1 and curr_row['macd_z'] <= 0):
                # 1% buffer for slip/fees
                if (curr_opt_price * contracts * 100) > (total_cost * 1.01): 
                    return 1
                elif i > 120: # Stuck for 2 hours, exit break-even
                    return 1 if (curr_opt_price * contracts * 100) > total_cost else 0
            
            # Exit: Stop Loss
            stop_hit = (direction == 1 and curr_row['Close'] < (entry_row['Close'] - (atr * self.profile.atr_mult))) or \
                       (direction == -1 and curr_row['Close'] > (entry_row['Close'] + (atr * self.profile.atr_mult)))
            if stop_hit: return 0 
                
            # Exit: EOD
            if ts.hour == 15 and ts.minute >= 55:
                return 1 if (curr_opt_price * contracts * 100) > total_cost else 0
        return 0

    async def run_backtest(self) -> Dict[str, Any]:
        """Runs the full historical backtest based on profile thresholds."""
        df = self._load_historical_data()
        df = calculate_indicators(df)
        
        # Signal Generation based on profile settings
        df['signal'] = 0
        df.loc[(df['macd_z'] < -self.profile.z_threshold_call) & (df['vol_z'] > self.profile.vol_threshold), 'signal'] = 1
        df.loc[(df['macd_z'] > self.profile.z_threshold_put) & (df['vol_z'] > self.profile.vol_threshold), 'signal'] = 1
        
        signals = df[(df['signal'] == 1) & 
                    (df['mins_open'] >= self.profile.start_time_min) & 
                    (df['mins_open'] < self.profile.entry_cutoff_min)].index
        
        campaigns = []
        for idx in signals:
            loc = df.index.get_loc(idx)
            if loc > len(df) - 241: continue
            
            # Yield for responsiveness
            if len(campaigns) % 50 == 0: await asyncio.sleep(0)
            
            result = self.simulate_campaign(df, loc)
            campaigns.append({
                'timestamp': idx.isoformat(),
                'atr': float(df.at[idx, 'atr']),
                'mins_open': int(df.at[idx, 'mins_open']),
                'macd_z': float(df.at[idx, 'macd_z']),
                'vol_z': float(df.at[idx, 'vol_z']),
                'implied_vol': float(df.at[idx, 'implied_vol']),
                'target': result
            })
            
        # Export for Trainer
        results_df = pd.DataFrame(campaigns)
        results_df.to_csv(self.output_file, index=False)
        
        return self._generate_audit(results_df)

    def _generate_audit(self, df: pd.DataFrame) -> Dict[str, Any]:
        """Calculates audit metrics for the dashboard visualization."""
        if df.empty:
            return {"status": "No signals found"}
            
        wins = df[df['target'] == 1]
        losses = df[df['target'] == 0]
        
        win_rate = len(wins) / len(df)
        profit_factor = len(wins) / len(losses) if len(losses) > 0 else float(len(wins))
        
        # Hourly Breakdown
        df['hour'] = (df['mins_open'] // 60).astype(int)
        hourly = df.groupby('hour')['target'].agg(['count', 'mean']).to_dict('index')
        
        # Trade Type Breakdown
        df['type'] = df['macd_z'].apply(lambda x: 'Call' if x < 0 else 'Put')
        types = df.groupby('type')['target'].agg(['count', 'mean']).to_dict('index')
        
        return {
            "summary": {
                "total_campaigns": len(df),
                "win_rate": win_rate,
                "profit_factor": profit_factor,
                "avg_vol": df['implied_vol'].mean()
            },
            "hourly_performance": hourly,
            "type_performance": types,
            "recent_trades": df.tail(10).to_dict('records')
        }